// const gridSatisfiedObject = [
//     {'Afecto': [
//         'Afectuos@',
//         'Amoros@',
//         'Cariños@',
//         'Compasiv@',
//         'Comprensiv@',
//         'Simpátic@',
//         'Tiern@',
//         ]
//     },
//     {'Confianza': [
//         'Capaz',
//         'Confiad@',
//         'Fuerte',
//         'Illusionad@',
//         'Orgullos@',
//         'Recepetiv@',
//         'Segur@',
//         ]
//     },
//     {'Esperanza': [
//         'Alentad@',
//         'Esperanzad@',
//         'Espectante',
//         'Optimist@',
//         ]
//     },
// ];

const needsMet = [
    { category: 'Esperanza', name: 'Alentad@' },
    { category: 'Esperanza', name: 'Esperanzad@' },
    { category: 'Esperanza', name: 'Espectante' },
    { category: 'Esperanza', name: 'Optimist@' },

    { category: 'Confianza', name: 'Capaz'},
    { category: 'Confianza', name: 'Confiad@'},
    { category: 'Confianza', name: 'Fuerte'},
    { category: 'Confianza', name: 'Illusionad@'},
    { category: 'Confianza', name: 'Orgullos@'},
    { category: 'Confianza', name: 'Recepetiv@'},
    { category: 'Confianza', name: 'Segur@'},

    { category: 'Afecto', name: 'Afectuos@'},
    { category: 'Afecto', name: 'Amoros@'},
    { category: 'Afecto', name: 'Cariños@'},
    { category: 'Afecto', name: 'Compasiv@'},
    { category: 'Afecto', name: 'Comprensiv@'},
    { category: 'Afecto', name: 'Simpátic@'},
    { category: 'Afecto', name: 'Tiern@'},

    { category: 'Euforia', name: 'Eufóric@'},
    { category: 'Euforia', name: 'Exultante'},
    { category: 'Euforia', name: 'Efusiv@'},

    { category: 'Inspiración', name: 'Impresionad@'},
    { category: 'Inspiración', name: 'Inspirad@'},
    { category: 'Inspiración', name: 'Maravillad@'},
    { category: 'Inspiración', name: 'Parad@'},

    { category: 'Interés', name: 'Abiert@'},
    { category: 'Interés', name: 'Atent@'},
    { category: 'Interés', name: 'Atraíd@'},
    { category: 'Interés', name: 'Comprometid@'},
    { category: 'Interés', name: 'Curios@'},
    { category: 'Interés', name: 'Decidid@'},
    { category: 'Interés', name: 'Dispuest@'},
    { category: 'Interés', name: 'Inspirad@'},
    { category: 'Interés', name: 'Interesad@'},
    { category: 'Interés', name: 'Intrigad@'},
    { category: 'Interés', name: 'Involucrad@'},
    { category: 'Interés', name: 'Motivad@'},

    { category: 'Descanso', name: 'Descansad@'},
    { category: 'Descanso', name: 'Refrescad@'},
    { category: 'Descanso', name: 'Renovad@'},
    { category: 'Descanso', name: 'Reposad@'},
    { category: 'Descanso', name: 'Restaurad@'},

    { category: 'Entusiasmo', name: 'Animad@'},
    { category: 'Entusiasmo', name: 'Apasionad@'},
    { category: 'Entusiasmo', name: 'Entusiasmad@'},
    { category: 'Entusiasmo', name: 'Estimulad@'},
    { category: 'Entusiasmo', name: 'Exitad@'},
    { category: 'Entusiasmo', name: 'Fascinad@'},
    { category: 'Entusiasmo', name: 'Illusionad@'},
    { category: 'Entusiasmo', name: 'Impresionad@'},
    { category: 'Entusiasmo', name: 'Sorprendid@'},

    { category: 'Paz', name: 'Aliviad@'},
    { category: 'Paz', name: 'Sosegad@'},
    { category: 'Paz', name: 'Calmad@'},
    { category: 'Paz', name: 'Centrad@'},
    { category: 'Paz', name: 'Cercan@'},
    { category: 'Paz', name: 'Cómod@'},
    { category: 'Paz', name: 'Content@'},
    { category: 'Paz', name: 'Desahogad@'},
    { category: 'Paz', name: 'Despreocupad@'},
    { category: 'Paz', name: 'Lúcid@'},
    { category: 'Paz', name: 'Plácid@'},
    { category: 'Paz', name: 'Realizad@'},
    { category: 'Paz', name: 'Relajad@'},
    { category: 'Paz', name: 'Satisfech@'},

    { category: 'Felicidad', name: 'Alegre'},
    { category: 'Felicidad', name: 'Complacid@'},
    { category: 'Felicidad', name: 'Feliz'},
    { category: 'Felicidad', name: 'Gozos@'},

    { category: 'Gratitud', name: 'Agradecid@'},
    { category: 'Gratitud', name: 'Conmovid@'},
    { category: 'Gratitud', name: 'Emocionad@'},
    { category: 'Gratitud', name: 'Generos@'},

];

const unmetMet = [
    { category:'Anhelo', name:'Añorad@'},
    { category:'Anhelo', name:'Celos@'},
    { category:'Anhelo', name:'Deseos@'},
    { category:'Anhelo', name:'Envidios@'},
    { category:'Anhelo', name:'Melancólic@'},
    { category:'Anhelo', name:'Nostálgic@'},
    { category:'Anhelo', name:'Sol@'},

    { category:'Aversión', name:'Asco'},
    { category:'Aversión', name:'Horrorizad@'},
    { category:'Aversión', name:'Desprecio'},
    { category:'Aversión', name:'Odio'},
    { category:'Aversión', name:'Repugnad@'},

    { category:'Desconexión', name:'Aburrid@'},
    { category:'Desconexión', name:'Afectad@'},
    { category:'Desconexión', name:'Aislad@'},
    { category:'Desconexión', name:'Apátic@'},
    { category:'Desconexión', name:'Desconectad@'},
    { category:'Desconexión', name:'Desidios@'},
    { category:'Desconexión', name:'Distante'},
    { category:'Desconexión', name:'Frí@'},
    { category:'Desconexión', name:'Indiferente'},
    { category:'Desconexión', name:'Reprochad@'},

    { category:'Enfadado', name:'Disgustad@'},
    { category:'Enfadado', name:'Enfadad@'},
    { category:'Enfadado', name:'Furios@'},
    { category:'Enfadado', name:'Indignad@'},
    { category:'Enfadado', name:'Molest@'},
    { category:'Enfadado', name:'Resenti@'},
    { category:'Tensión', name:'Ansios@'},
    { category:'Tensión', name:'Conmocionad@'},
    { category:'Tensión', name:'Desbordad@'},
    { category:'Tensión', name:'Estresad@'},
    { category:'Tensión', name:'Irritable'},
    { category:'Tensión', name:'Nervios@'},
    { category:'Tensión', name:'Sobrecarg@'},
    { category:'Tensión', name:'Sobrepasad@'},
    { category:'Tensión', name:'Tens@'},

    { category:'Miedo', name:'Acongojad@'},
    { category:'Miedo', name:'Asustad@'},
    { category:'Miedo', name:'Atemorizad@'},
    { category:'Miedo', name:'Aterrorizad@'},
    { category:'Miedo', name:'Desconfiad@'},
    { category:'Miedo', name:'Preocupad@'},

    { category:'Cansancio', name:'Abatid@'},
    { category:'Cansancio', name:'Agotad@'},
    { category:'Cansancio', name:'Cansad@'},
    { category:'Cansancio', name:'Débil'},
    { category:'Cansancio', name:'Dolorid@'},
    { category:'Cansancio', name:'Fatigad@'},
    { category:'Cansancio', name:'Afligad@'},
    { category:'Cansancio', name:'Angustiad@'},
    { category:'Cansancio', name:'Desconsolad@'},
    { category:'Cansancio', name:'Deshech@'},

    { category:'Confusión', name:'Bloquead@'},
    { category:'Confusión', name:'Confus@'},
    { category:'Confusión', name:'Desorientad@'},
    { category:'Confusión', name:'Dividid@'},
    { category:'Confusión', name:'Dudos@'},
    { category:'Confusión', name:'Escéptic@'},
    { category:'Confusión', name:'Indescis@'},
    { category:'Confusión', name:'Pensativ@'},
    { category:'Confusión', name:'Perdid@'},
    { category:'Confusión', name:'Perplej@'},
    { category:'Confusión', name:'Vacilante'},

    { category:'Inquietud', name:'Agitad@'},
    { category:'Inquietud', name:'Agobiad@'},
    { category:'Inquietud', name:'Alarmad@'},
    { category:'Inquietud', name:'Arrepetid@'},
    { category:'Inquietud', name:'Avergonzad@'},
    { category:'Inquietud', name:'Desconcertad@'},
    { category:'Inquietud', name:'Escandalizad@'},
    { category:'Inquietud', name:'Incómod@'},
    { category:'Inquietud', name:'Inquiet@'},
    { category:'Inquietud', name:'Intranquil@'},
    { category:'Inquietud', name:'Preocupad@'},
    { category:'Inquietud', name:'Sobresaltad@'},
    { category:'Inquietud', name:'Sorprendid@'},

    { category:'Irritación', name:'Consternad@'},
    { category:'Irritación', name:'Frustrad@'},
    { category:'Irritación', name:'Impaciente'},
    { category:'Irritación', name:'Irritad@'},
    { category:'Irritación', name:'Malhumorad@'},
    { category:'Irritación', name:'Molest@'},

    { category:'Vulnerabilidad', name:'Frágil'},
    { category:'Vulnerabilidad', name:'Impotente'},
    { category:'Vulnerabilidad', name:'Insegur@'},
    { category:'Vulnerabilidad', name:'Sensible'},
    { category:'Vulnerabilidad', name:'Tímid@'},
    { category:'Vulnerabilidad', name:'Vulnerable'},

    { category:'Tristeza', name:'Decepcionad@'},
    { category:'Tristeza', name:'Deprimid@'},
    { category:'Tristeza', name:'Desanimad@'},
    { category:'Tristeza', name:'Desgraciad@'},
    { category:'Tristeza', name:'Desilusionad@'},
    { category:'Tristeza', name:'Infeliz'},
    { category:'Tristeza', name:'Triste'},
]

const moods = [
    ...needsMet,
    ...unmetMet,
];

export default moods;
